#pragma once

#define IDI_MAIN_PROGRAM 101
#define IDI_PREFERENCES  102
#define IDB_START_ORB    103

#define IDD_TASKBAR_PROPS     201
#define IDC_LOCK_TASKBAR      202
#define IDC_AUTOHIDE_TASKBAR  203
#define IDC_SMALL_ICONS       204
#define IDC_STATIC            -1

#define IDD_STARTMENU_PROPS   205
#define IDD_DESKTOP_PROPS     206
#define IDD_TOOLBARS_PROPS    207
#define IDD_SECRET_EVERYTHING 208
#define IDD_SECRET_DLLSCANNER 209

#define IDC_MODE_INDEPENDENT  210
#define IDC_MODE_REPLACE      211

// Taskbar UI
#define IDC_TRAY_NATIVE       212
#define IDC_TRAY_LEGACY       213
#define IDC_MONITOR_LIST      214
#define IDC_COMPONENTS_LIST   215

// Start Menu UI
#define IDC_START_OPENSHELL   216
#define IDC_START_NATIVE      217
#define IDC_START_COMBO       218
#define IDC_START_TRIGGER     219

// Toolbars UI
#define IDC_TOOLBAR_LIST      220
#define IDC_TOOLBAR_NEW       221
